Crafty.defineScene('Scores', function () {
    var Game, h, i, scores, w;
    Game = window.Game;
    Game.resetCredits();
    Crafty.background('#000000');
    Crafty.viewport.x = 0;
    Crafty.viewport.y = 0;
    w = Crafty.viewport.width;
    h = Crafty.viewport.height;
    Crafty.e('2D, DOM, Text').attr({
        x: 0,
        y: h * .1,
        w: w
    }).text('Highscores').textColor('#FFFF00').textAlign('center').textFont({
        size: '40px',
        weight: 'bold',
        family: 'Press Start 2P'
    });
    scores = Game.highscores();
    i = 0;
    Crafty.e('Delay').delay(function () {
        var entry, nr, size;
        entry = scores[i];
        if (entry) {
            nr = (function () {
                switch (i) {
                    case 0:
                        return 'ACE';
                    case 1:
                        return '2nd';
                    case 2:
                        return '3rd';
                    default:
                        return (i + 1) + "th";
                }
            })();
            size = (function () {
                switch (i) {
                    case 0:
                        return '20px';
                    case 1:
                    case 2:
                        return '18px';
                    default:
                        return '15px';
                }
            })();
            Crafty.e('2D, DOM, Text').attr({
                x: 0,
                y: (h * .25) + (36 * i),
                w: w
            }).text(nr + "  " + entry.score + " " + entry.initials).textColor('#FFFF00').textAlign('center').textFont({
                size: size,
                weight: 'bold',
                family: 'Press Start 2P'
            });
            return i += 1;
        }
    }, 500, 9);
    Crafty('Player').each(function () {
        this.reset();
        return this.one('Activated', function () {
            return Crafty.enterScene(Game.firstLevel);
        });
    });
    return Crafty.e('Delay').delay(function () {
        return Crafty.enterScene('Intro');
    }, 20000);
}, function () {
    Crafty('Delay').each(function () {
        return this.destroy();
    });
    return Crafty('Player').each(function () {
        return this.unbind('Activated');
    });
});

// ---
// generated by coffee-script 1.9.2